### ISSUE TITLE
Cargo.toml gets written out of the original order

### ISSUE THREAD

**Issue by pwoolcoc** [pwoolcoc/cargo-template#8]
Right now when we fill in the `name` and `author` sections in the `Cargo.toml`, the `package` section gets written to the bottom of the file, instead of the top. This should be fixed so that the `package` section retains it's spot at the top of the file.

**Comment by ssokolow** [comment]
It's worse than that. It flat-out mangles comments into invalid TOML.

Here's a before/after for a template I'm putting together for myself:

Before:
```toml
[package]
name = "{{toml-escape name}}"
version = "0.1.0"
authors = ["{{toml-escape author}}"]

[dependencies]
clap = "2"

[dependencies.error-chain]
version = "0.9"
default-features = false  # disable pulling in backtrace

[profile.release]
lto = true
panic = 'abort'

# We need to specify this explicitly so sed can swap the 3 for "z" in
# release.sh when running with --nightly
opt-level = 3

[features]
nightly = []

```

After:
```toml
[dependencies]
clap = "2"

[dependencies.error-chain]
default-features = false
version = "0.9"

[features]
nightly = []

[package]
authors = ["Stephan Sokolow <http://www.ssokolow.com/ContactMe>"]
name = "rust_test"
version = "0.1.0"

[profile]
[profile.release]
lto = true
opt-level = 3
panic = "abort"
n swap the 3 for "z" in
# release.sh when running with --nightly
opt-level = 3

[features]
nightly = []
```
